### ISSUE TITLE
'Main' object has no attribute 'driver'

### ISSUE THREAD

**Issue by cldborges** [xtekky/google-login-bypass#3]
Hello. When I run your code, the Chrome doesn't open and I receive this error:

Traceback (most recent call last):
  File "g:\Meu Drive\Python\Projetos\Jogos gratis Epic Games\teste-google-login-bypass", line 31, in <module>
    driver.login(email, password)
  File "g:\Meu Drive\Python\Projetos\Jogos gratis Epic Games\teste-google-login-bypass", line 15, in login
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.NAME, 'identifier'))).send_keys(f'{email}\n')
AttributeError: 'Main' object has no attribute 'driver'

I'm trying to make a automation that enter in Epic Games site and "buy" week free games
https://github.com/cldborges/Jogos-gratis-Epic-Games

Thanks

**Comment by backupandforkacc** [comment]
Traceback (most recent call last):
  File "c:\getgooglecookies.py", line 29, in <module>
    driver.login(email, password)
  File "c:\getgooglecookies.py", line 13, in login
    WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.NAME, 'identifier'))).send_keys(f'{email}\n')
AttributeError: 'Main' object has no attribute 'driver'

**Comment by xtekky** [comment]
issue solved
